//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/004-Scripts/UserInput/UserInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UserInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UserInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UserInput"",
    ""maps"": [
        {
            ""name"": ""Drone"",
            ""id"": ""74830570-94ea-4df4-a9e7-690fa1db7337"",
            ""actions"": [
                {
                    ""name"": ""Thrust"",
                    ""type"": ""Value"",
                    ""id"": ""36406cc6-a007-43e8-a19e-f220426bcb7e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""3976c6f1-32d0-48ea-a92a-621e3fc6de73"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ef30833e-5d57-4050-805e-600ed12ca0d6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b227c4bf-154f-4934-9acf-1e28e196f3bc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""01455861-357d-4e46-b499-c6dcdc3f88e5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b137e9b8-4942-4d3b-80b2-759e5b6dfdc3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Crew"",
            ""id"": ""24ca4ed4-1d5a-4568-afb1-99165889a2ef"",
            ""actions"": [
                {
                    ""name"": ""Walk"",
                    ""type"": ""Value"",
                    ""id"": ""4ab16952-dda2-47f8-8965-7ef2159c608c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""212e8575-301f-4cd2-88b0-9d98b17d888c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f5bde55c-c336-41f7-ba30-f1b4289ddd81"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b62f3375-ec11-4ded-9301-aa06e6a75b03"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cc305768-8d16-42a3-8b53-dd5468fce6e3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""55412a3a-e900-4b95-bfa6-8122678871af"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""User"",
            ""id"": ""0916df10-d4f5-449a-bb69-bd1d6b14ab58"",
            ""actions"": [
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""f104975c-93f0-46fd-88b9-bf10f4e01274"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shift"",
                    ""type"": ""Button"",
                    ""id"": ""1fd2563a-a195-4dff-bbef-c86bd848fe56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle"",
                    ""type"": ""Button"",
                    ""id"": ""5a1d6b75-a28e-4742-911b-00a52ff46439"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Index0"",
                    ""type"": ""Button"",
                    ""id"": ""ba889d7a-14b7-4cea-a2dd-2d90ab387aeb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Index1"",
                    ""type"": ""Button"",
                    ""id"": ""aca08eea-33cc-4a1d-b38f-1a1b3f0287cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Index2"",
                    ""type"": ""Button"",
                    ""id"": ""0e485948-3267-42d0-9301-3ee8d6fc4d1d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Index3"",
                    ""type"": ""Button"",
                    ""id"": ""9f9a2fe7-c16d-46fc-9975-bc8a7a5c7ed2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Index4"",
                    ""type"": ""Button"",
                    ""id"": ""9dfb1b95-5801-4162-a3d8-b87137e7aa60"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Index5"",
                    ""type"": ""Button"",
                    ""id"": ""96a8b88a-5003-478f-a544-91142a31ec5e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Index6"",
                    ""type"": ""Button"",
                    ""id"": ""d9a69be0-8c0c-4f28-a23d-c42a0b6d05c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Index7"",
                    ""type"": ""Button"",
                    ""id"": ""18ea9b42-2f88-43e1-9e06-1922df9f3d7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Index8"",
                    ""type"": ""Button"",
                    ""id"": ""43e232e3-674d-4720-9a84-69c71fe93403"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Index9"",
                    ""type"": ""Button"",
                    ""id"": ""669370e8-9d3d-4d5b-8ade-66d6049ddf77"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6c53143a-5a0c-40eb-857c-b4ecd5ea1bcf"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a8b1b90-f1f1-44bb-a885-59e945f71a13"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83a7b5bb-009a-4c89-8524-21a5a13d1f7c"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Index1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fca5dfd-d768-48cd-8175-a88c65e72500"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Index2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a56d96c6-3785-482b-b6f4-d8a708e6f19f"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Index3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8bebf65-b369-4944-a59a-33fc545ac70b"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Index4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a68dbc64-c387-4581-a2e1-b271cbf23579"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Index5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f239ac64-6cf4-4b77-8293-c2867564f72f"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Index6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8e576dd-d8a8-4a6e-ab77-a4dec2a659d8"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Index7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6e4d844-b267-4ddd-bd46-ac43007d9e0c"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Index8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c280e252-ec33-47dd-bc9b-bc1d46aa622f"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Index9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7624771a-d7e3-4fa9-9f67-8b7ed381b1af"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Index0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fa39c67-cc18-453f-ac2c-780ba4fa7623"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Admin"",
            ""id"": ""c0aba9b0-88f3-4b8f-be23-caa80918b836"",
            ""actions"": [
                {
                    ""name"": ""Toggle"",
                    ""type"": ""Button"",
                    ""id"": ""f551f81e-ee91-447d-85e8-58254180249f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Materium"",
                    ""type"": ""Button"",
                    ""id"": ""7dd92d92-48fc-4644-b8bd-75f3a8ecc6ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3ed1826c-5444-40eb-9e9b-1a450988523e"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cede295a-05dc-4480-9aa4-2e772838a31a"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Materium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Drone
        m_Drone = asset.FindActionMap("Drone", throwIfNotFound: true);
        m_Drone_Thrust = m_Drone.FindAction("Thrust", throwIfNotFound: true);
        // Crew
        m_Crew = asset.FindActionMap("Crew", throwIfNotFound: true);
        m_Crew_Walk = m_Crew.FindAction("Walk", throwIfNotFound: true);
        // User
        m_User = asset.FindActionMap("User", throwIfNotFound: true);
        m_User_Quit = m_User.FindAction("Quit", throwIfNotFound: true);
        m_User_Shift = m_User.FindAction("Shift", throwIfNotFound: true);
        m_User_Toggle = m_User.FindAction("Toggle", throwIfNotFound: true);
        m_User_Index0 = m_User.FindAction("Index0", throwIfNotFound: true);
        m_User_Index1 = m_User.FindAction("Index1", throwIfNotFound: true);
        m_User_Index2 = m_User.FindAction("Index2", throwIfNotFound: true);
        m_User_Index3 = m_User.FindAction("Index3", throwIfNotFound: true);
        m_User_Index4 = m_User.FindAction("Index4", throwIfNotFound: true);
        m_User_Index5 = m_User.FindAction("Index5", throwIfNotFound: true);
        m_User_Index6 = m_User.FindAction("Index6", throwIfNotFound: true);
        m_User_Index7 = m_User.FindAction("Index7", throwIfNotFound: true);
        m_User_Index8 = m_User.FindAction("Index8", throwIfNotFound: true);
        m_User_Index9 = m_User.FindAction("Index9", throwIfNotFound: true);
        // Admin
        m_Admin = asset.FindActionMap("Admin", throwIfNotFound: true);
        m_Admin_Toggle = m_Admin.FindAction("Toggle", throwIfNotFound: true);
        m_Admin_Materium = m_Admin.FindAction("Materium", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Drone
    private readonly InputActionMap m_Drone;
    private IDroneActions m_DroneActionsCallbackInterface;
    private readonly InputAction m_Drone_Thrust;
    public struct DroneActions
    {
        private @UserInput m_Wrapper;
        public DroneActions(@UserInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Thrust => m_Wrapper.m_Drone_Thrust;
        public InputActionMap Get() { return m_Wrapper.m_Drone; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DroneActions set) { return set.Get(); }
        public void SetCallbacks(IDroneActions instance)
        {
            if (m_Wrapper.m_DroneActionsCallbackInterface != null)
            {
                @Thrust.started -= m_Wrapper.m_DroneActionsCallbackInterface.OnThrust;
                @Thrust.performed -= m_Wrapper.m_DroneActionsCallbackInterface.OnThrust;
                @Thrust.canceled -= m_Wrapper.m_DroneActionsCallbackInterface.OnThrust;
            }
            m_Wrapper.m_DroneActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Thrust.started += instance.OnThrust;
                @Thrust.performed += instance.OnThrust;
                @Thrust.canceled += instance.OnThrust;
            }
        }
    }
    public DroneActions @Drone => new DroneActions(this);

    // Crew
    private readonly InputActionMap m_Crew;
    private ICrewActions m_CrewActionsCallbackInterface;
    private readonly InputAction m_Crew_Walk;
    public struct CrewActions
    {
        private @UserInput m_Wrapper;
        public CrewActions(@UserInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Walk => m_Wrapper.m_Crew_Walk;
        public InputActionMap Get() { return m_Wrapper.m_Crew; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CrewActions set) { return set.Get(); }
        public void SetCallbacks(ICrewActions instance)
        {
            if (m_Wrapper.m_CrewActionsCallbackInterface != null)
            {
                @Walk.started -= m_Wrapper.m_CrewActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_CrewActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_CrewActionsCallbackInterface.OnWalk;
            }
            m_Wrapper.m_CrewActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
            }
        }
    }
    public CrewActions @Crew => new CrewActions(this);

    // User
    private readonly InputActionMap m_User;
    private IUserActions m_UserActionsCallbackInterface;
    private readonly InputAction m_User_Quit;
    private readonly InputAction m_User_Shift;
    private readonly InputAction m_User_Toggle;
    private readonly InputAction m_User_Index0;
    private readonly InputAction m_User_Index1;
    private readonly InputAction m_User_Index2;
    private readonly InputAction m_User_Index3;
    private readonly InputAction m_User_Index4;
    private readonly InputAction m_User_Index5;
    private readonly InputAction m_User_Index6;
    private readonly InputAction m_User_Index7;
    private readonly InputAction m_User_Index8;
    private readonly InputAction m_User_Index9;
    public struct UserActions
    {
        private @UserInput m_Wrapper;
        public UserActions(@UserInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Quit => m_Wrapper.m_User_Quit;
        public InputAction @Shift => m_Wrapper.m_User_Shift;
        public InputAction @Toggle => m_Wrapper.m_User_Toggle;
        public InputAction @Index0 => m_Wrapper.m_User_Index0;
        public InputAction @Index1 => m_Wrapper.m_User_Index1;
        public InputAction @Index2 => m_Wrapper.m_User_Index2;
        public InputAction @Index3 => m_Wrapper.m_User_Index3;
        public InputAction @Index4 => m_Wrapper.m_User_Index4;
        public InputAction @Index5 => m_Wrapper.m_User_Index5;
        public InputAction @Index6 => m_Wrapper.m_User_Index6;
        public InputAction @Index7 => m_Wrapper.m_User_Index7;
        public InputAction @Index8 => m_Wrapper.m_User_Index8;
        public InputAction @Index9 => m_Wrapper.m_User_Index9;
        public InputActionMap Get() { return m_Wrapper.m_User; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UserActions set) { return set.Get(); }
        public void SetCallbacks(IUserActions instance)
        {
            if (m_Wrapper.m_UserActionsCallbackInterface != null)
            {
                @Quit.started -= m_Wrapper.m_UserActionsCallbackInterface.OnQuit;
                @Quit.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnQuit;
                @Quit.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnQuit;
                @Shift.started -= m_Wrapper.m_UserActionsCallbackInterface.OnShift;
                @Shift.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnShift;
                @Shift.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnShift;
                @Toggle.started -= m_Wrapper.m_UserActionsCallbackInterface.OnToggle;
                @Toggle.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnToggle;
                @Toggle.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnToggle;
                @Index0.started -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex0;
                @Index0.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex0;
                @Index0.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex0;
                @Index1.started -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex1;
                @Index1.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex1;
                @Index1.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex1;
                @Index2.started -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex2;
                @Index2.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex2;
                @Index2.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex2;
                @Index3.started -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex3;
                @Index3.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex3;
                @Index3.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex3;
                @Index4.started -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex4;
                @Index4.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex4;
                @Index4.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex4;
                @Index5.started -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex5;
                @Index5.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex5;
                @Index5.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex5;
                @Index6.started -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex6;
                @Index6.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex6;
                @Index6.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex6;
                @Index7.started -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex7;
                @Index7.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex7;
                @Index7.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex7;
                @Index8.started -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex8;
                @Index8.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex8;
                @Index8.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex8;
                @Index9.started -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex9;
                @Index9.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex9;
                @Index9.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnIndex9;
            }
            m_Wrapper.m_UserActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Quit.started += instance.OnQuit;
                @Quit.performed += instance.OnQuit;
                @Quit.canceled += instance.OnQuit;
                @Shift.started += instance.OnShift;
                @Shift.performed += instance.OnShift;
                @Shift.canceled += instance.OnShift;
                @Toggle.started += instance.OnToggle;
                @Toggle.performed += instance.OnToggle;
                @Toggle.canceled += instance.OnToggle;
                @Index0.started += instance.OnIndex0;
                @Index0.performed += instance.OnIndex0;
                @Index0.canceled += instance.OnIndex0;
                @Index1.started += instance.OnIndex1;
                @Index1.performed += instance.OnIndex1;
                @Index1.canceled += instance.OnIndex1;
                @Index2.started += instance.OnIndex2;
                @Index2.performed += instance.OnIndex2;
                @Index2.canceled += instance.OnIndex2;
                @Index3.started += instance.OnIndex3;
                @Index3.performed += instance.OnIndex3;
                @Index3.canceled += instance.OnIndex3;
                @Index4.started += instance.OnIndex4;
                @Index4.performed += instance.OnIndex4;
                @Index4.canceled += instance.OnIndex4;
                @Index5.started += instance.OnIndex5;
                @Index5.performed += instance.OnIndex5;
                @Index5.canceled += instance.OnIndex5;
                @Index6.started += instance.OnIndex6;
                @Index6.performed += instance.OnIndex6;
                @Index6.canceled += instance.OnIndex6;
                @Index7.started += instance.OnIndex7;
                @Index7.performed += instance.OnIndex7;
                @Index7.canceled += instance.OnIndex7;
                @Index8.started += instance.OnIndex8;
                @Index8.performed += instance.OnIndex8;
                @Index8.canceled += instance.OnIndex8;
                @Index9.started += instance.OnIndex9;
                @Index9.performed += instance.OnIndex9;
                @Index9.canceled += instance.OnIndex9;
            }
        }
    }
    public UserActions @User => new UserActions(this);

    // Admin
    private readonly InputActionMap m_Admin;
    private IAdminActions m_AdminActionsCallbackInterface;
    private readonly InputAction m_Admin_Toggle;
    private readonly InputAction m_Admin_Materium;
    public struct AdminActions
    {
        private @UserInput m_Wrapper;
        public AdminActions(@UserInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Toggle => m_Wrapper.m_Admin_Toggle;
        public InputAction @Materium => m_Wrapper.m_Admin_Materium;
        public InputActionMap Get() { return m_Wrapper.m_Admin; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AdminActions set) { return set.Get(); }
        public void SetCallbacks(IAdminActions instance)
        {
            if (m_Wrapper.m_AdminActionsCallbackInterface != null)
            {
                @Toggle.started -= m_Wrapper.m_AdminActionsCallbackInterface.OnToggle;
                @Toggle.performed -= m_Wrapper.m_AdminActionsCallbackInterface.OnToggle;
                @Toggle.canceled -= m_Wrapper.m_AdminActionsCallbackInterface.OnToggle;
                @Materium.started -= m_Wrapper.m_AdminActionsCallbackInterface.OnMaterium;
                @Materium.performed -= m_Wrapper.m_AdminActionsCallbackInterface.OnMaterium;
                @Materium.canceled -= m_Wrapper.m_AdminActionsCallbackInterface.OnMaterium;
            }
            m_Wrapper.m_AdminActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Toggle.started += instance.OnToggle;
                @Toggle.performed += instance.OnToggle;
                @Toggle.canceled += instance.OnToggle;
                @Materium.started += instance.OnMaterium;
                @Materium.performed += instance.OnMaterium;
                @Materium.canceled += instance.OnMaterium;
            }
        }
    }
    public AdminActions @Admin => new AdminActions(this);
    public interface IDroneActions
    {
        void OnThrust(InputAction.CallbackContext context);
    }
    public interface ICrewActions
    {
        void OnWalk(InputAction.CallbackContext context);
    }
    public interface IUserActions
    {
        void OnQuit(InputAction.CallbackContext context);
        void OnShift(InputAction.CallbackContext context);
        void OnToggle(InputAction.CallbackContext context);
        void OnIndex0(InputAction.CallbackContext context);
        void OnIndex1(InputAction.CallbackContext context);
        void OnIndex2(InputAction.CallbackContext context);
        void OnIndex3(InputAction.CallbackContext context);
        void OnIndex4(InputAction.CallbackContext context);
        void OnIndex5(InputAction.CallbackContext context);
        void OnIndex6(InputAction.CallbackContext context);
        void OnIndex7(InputAction.CallbackContext context);
        void OnIndex8(InputAction.CallbackContext context);
        void OnIndex9(InputAction.CallbackContext context);
    }
    public interface IAdminActions
    {
        void OnToggle(InputAction.CallbackContext context);
        void OnMaterium(InputAction.CallbackContext context);
    }
}
